import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { StoreHydrator } from "@/components/layout/StoreHydrator";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <div className="fixed inset-0 acid-grain pointer-events-none" aria-hidden />
        <StoreHydrator>{children}</StoreHydrator>
        <Toaster theme="dark" toastOptions={{ style: { background: "hsl(240 3.7% 11.9%)", borderColor: "hsl(0 100% 60%)" } }} />
      </body>
    </html>
  );
}
